---
- name: Upgrade NS to current version
  block:
    - name: Upgrade commands
      shell: |
        mount -F nfs 10.3.70.8:/volumes/alpo/qa_depot /mnt/
        lofiadm -a /mnt/"{{ update_iso_path }}"
        mkdir /media/NS_UpgradeCD
        mount -F hsfs /dev/lofi/1 /media/NS_UpgradeCD
        nmc -c "setup appliance upgrade -yvc"
      ignore_errors: true

    - name: Delay for 10 minutes for Upgrade proccess
      pause:
       seconds: 600
  when: upgrade_to_fp
  rescue:
   - debug:
       msg: 'UNABLE TO UPGRADE'
...
