---
        - name: Random Delay
          pause:
            seconds: "{{ config_ci_delay | random }}"

        - name: Create Current Build Folder
          vcenter_folder:
            validate_certs: False
            hostname: "{{ config_vsphere_host }}"
            username: "{{ config_vsphere_user }}"
            password: "{{ config_vsphere_password }}"
            datacenter: "{{ config_vsphere_datacenter }}"
            parent_folder: "{{ config_vsphere_folder }}"
            folder_name: "Build_{{ config_ci_build }}"
            state: "present"

        - name: Destroy Virtual Machine
          vmware_guest:
            validate_certs: False
            hostname: "{{ config_vsphere_host }}"
            username: "{{ config_vsphere_user }}"
            password: "{{ config_vsphere_password }}"
            datacenter: "{{ config_vsphere_datacenter }}"
            cluster: "{{ config_vsphere_cluster }}"
            folder: "{{ config_vsphere_datacenter }}/vm/{{ config_vsphere_folder }}/Build_{{ config_ci_build }}"
            name: "{{ config_vm_name_4x }}"
            state: "absent"
            force: yes

        - name: Create Virtual Machine
          vmware_guest:
            validate_certs: False
            hostname: "{{ config_vsphere_host }}"
            username: "{{ config_vsphere_user }}"
            password: "{{ config_vsphere_password }}"
            datacenter: "{{ config_vsphere_datacenter }}"
            cluster: "{{ config_vsphere_cluster }}"
            folder: "{{ config_vsphere_datacenter }}/vm/{{ config_vsphere_folder }}/Build_{{ config_ci_build }}"
            name: "{{ config_vm_name_4x }}"
            guest_id: "{{ config_vm_guest }}"
            disk:
            - size_gb: 16
              type: thin
              datastore: "{{ config_vm_datastore }}"
            - size_gb: 32
              type: thin
              datastore: "{{ config_vm_datastore }}"
            hardware:
              memory_mb: 8192
              num_cpus: 2
              scsi: paravirtual
            networks:
            - name: "{{ config_vm_deploy_net }}"
              mac: "{{ config_vm_mac1 }}"
              device_type: vmxnet3
            - name: "{{ config_vm_lab_net }}"
              device_type: vmxnet3
            wait_for_ip_address: False
            state: "poweredon"
         
        - copy: content="{{ config_vm_ip_4x }}" dest=ns_ip

        - name: Delay for 10 minutes to Install proccess
          pause:
            seconds: 600
 
        - name: Add IP to VMName to inventory 
          add_host:
            name: "{{ config_vm_name_4x }}"
            ansible_ssh_host: "{{ config_vm_ip_4x }}"
            ansible_ssh_user: "{{ config_applaince_root }}"
            ansible_ssh_pass: "{{ config_applaince_root_pass_4x }}"
            ansible_connection: "ssh"
            ansible_ssh_private_key_file: "/root/.ssh/id_rsa.pub"
...
